#!/usr/bin/env python3
"""Drive each governance path against a running pilot gateway, over HTTP.

This is a runbook convenience and a smoke driver — not part of the runtime. It
uses the supported :class:`pilot.client.MCCGatewayClient` and, for the consensus
path, signs evaluator votes with the LOCAL evaluator keys generated by
``generate_pilot_config.py``. In a real deployment the evaluators are independent
services holding their own keys; here the driver plays all roles (agent, the N
evaluators, and — where needed — the operator) so the path can be demonstrated
end to end deterministically.

Usage (against the docker-compose pilot):
    MCC_GATEWAY_URL=http://127.0.0.1:8001 \
    MCC_GATEWAY_API_KEY=$MCC_GATEWAY_API_KEY \
    python deploy/pilot/pilot_driver.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
SECRETS = HERE / "secrets"
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "src"))

from mcc_core import SigningKey, issue_vote  # noqa: E402

from pilot.client import Decision, ExecutionOutcome, MCCGatewayClient  # noqa: E402

FAR_FUTURE = 4_000_000_000


def load_evaluator_keys(secrets_dir: Path = SECRETS) -> List[SigningKey]:
    """Load the local evaluator private keys (evaluator_*.pem) in order."""
    pems = sorted(secrets_dir.glob("evaluator_*.pem"))
    if not pems:
        raise FileNotFoundError(
            f"no evaluator_*.pem in {secrets_dir}; run generate_pilot_config.py first")
    return [SigningKey.from_pem_file(str(p), p.stem) for p in pems]


def sign_votes(
    eval_keys: List[SigningKey], *, action: str, payload: Dict[str, Any], actor: str,
    policy_hash: str, nonce: str, resource: Optional[str] = None, verdict: str = "ALLOW",
) -> List[Dict[str, Any]]:
    """N independent ALLOW votes bound to the challenge nonce + gateway policy hash."""
    return [
        issue_vote(k, evaluator_id=k.kid, verdict=verdict, action=action, payload=payload,
                   actor=actor, not_before=0, not_after=FAR_FUTURE, resource=resource,
                   policy_hash=policy_hash, nonce=nonce)
        for k in eval_keys
    ]


def consensus_execute(
    client: MCCGatewayClient, eval_keys: List[SigningKey], *, actor: str, action: str,
    context: Dict[str, Any], policy_hash: str, resource: Optional[str] = None,
    idempotency_key: Optional[str] = None,
) -> ExecutionOutcome:
    """Gateway-issued challenge → N-of-M signed votes → governed execute."""
    challenge = client.issue_challenge(actor=actor, action=action, resource=resource,
                                       context=context)
    votes = sign_votes(eval_keys, action=action, payload=context, actor=actor,
                       policy_hash=policy_hash, nonce=challenge["nonce"], resource=resource)
    return client.execute_with_consensus(
        votes=votes, actor=actor, action=action, resource=resource, context=context,
        nonce=challenge["nonce"], challenge_id=challenge["challenge_id"],
        idempotency_key=idempotency_key)


# Authority verdicts via /evaluate, using the committed pilot policy
# (gateway/pilot_policy.py).
EVALUATE_CASES = [
    ("ALLOW", "agent/payments-bot", "send_payment", {"amount": 1000}),
    ("CONSTRAIN", "agent/payments-bot", "send_payment", {"amount": 99000}),
    ("ESCALATE", "agent/nobody", "send_payment", {"amount": 100}),
    ("DENY", "agent/ops-bot", "delete_database", {}),
]


def run_evaluate_paths(client: MCCGatewayClient) -> List[str]:
    failures: List[str] = []
    for expected, identity, action, context in EVALUATE_CASES:
        r = client.propose(identity=identity, action=action, context=context)
        ok = r.decision.value == expected
        extra = f"  clamped→{r.forward_context}" if r.decision == Decision.CONSTRAIN else ""
        print(f"[{r.decision.value:9}] {identity} {action} {context}{extra}")
        if not ok:
            failures.append(f"{action} by {identity}: got {r.decision.value}, want {expected}")
    return failures


def main() -> int:
    url = os.environ.get("MCC_GATEWAY_URL", "http://127.0.0.1:8001")
    api_key = os.environ.get("MCC_GATEWAY_API_KEY", "")
    if not api_key:
        sys.exit("set MCC_GATEWAY_API_KEY (the agent X-API-Key)")
    client = MCCGatewayClient(url, api_key=api_key,
                              operator_key=os.environ.get("MCC_GATEWAY_OPERATOR_API_KEY"))

    print("== readiness ==")
    print(f"  ready={client.is_ready()}  health={client.health().get('status')}")

    print("\n== authority verdicts (/evaluate) ==")
    failures = run_evaluate_paths(client)

    print("\n== consensus → governed execution (/consensus) ==")
    policy_hash = client.health()["policy_hash"]
    eval_keys = load_evaluator_keys()
    out = consensus_execute(client, eval_keys, actor="agent/payments-bot",
                            action="notify_endpoint", context={"amount": 100},
                            policy_hash=policy_hash, idempotency_key="pilot-driver-1")
    print(f"  consensus execute → status={out.status} decision={out.decision}")
    if not out.executed:
        failures.append(f"consensus execute did not run: {out.reason}")

    print("\n== audit chain (/verify) ==")
    chain = client.verify_chain()
    print(f"  chain_valid={chain.get('valid')} entries={chain.get('entries')}")
    if not chain.get("valid"):
        failures.append("audit chain did not verify")

    if failures:
        print("\nPILOT DRIVER FAILED:")
        for f in failures:
            print(f"  - {f}")
        return 1
    print("\nPILOT DRIVER PASSED: four verdicts + governed consensus execution + valid audit chain.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
